language: node_js
node_js:
  - "node"
  - "12"
  - "10"
  - "8"

jobs:
  include:
    - stage: test
      script: npm run test:cover && npm run coveralls
    - stage: lint
      script: npm run test:lint
      node_js: lts

after_success:
  - npm run coveralls
